// <auto-generated />
using System;
using Fatura.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fatura.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719174704_PostgreSqlInitial")]
    partial class PostgreSqlInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fatura.Server.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Tipo", "Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Fatura.Server.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContaFinanceiraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaFinanceiraId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("UserId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Fatura.Server.Models.CompraRecorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContaFinanceiraId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaCobranca")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaFinanceiraId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("UserId");

                    b.ToTable("ComprasRecorrentes");
                });

            modelBuilder.Entity("Fatura.Server.Models.ContaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("UserId", "InstituicaoId", "Nome")
                        .IsUnique();

                    b.ToTable("ContasFinanceiras");
                });

            modelBuilder.Entity("Fatura.Server.Models.FaturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<double>("Orcamento")
                        .HasColumnType("double precision");

                    b.Property<bool>("Quitada")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Mes", "Ano", "UserId")
                        .IsUnique();

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("Fatura.Server.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Fatura.Server.Models.InstituicaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Nome")
                        .IsUnique();

                    b.ToTable("InstituicoesFinanceiras");
                });

            modelBuilder.Entity("Fatura.Server.Models.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("ContaFinanceiraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<int?>("OrigemId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaFinanceiraId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("Origem", "OrigemId")
                        .IsUnique()
                        .HasDatabaseName("UX_Lancamento_Origem");

                    b.HasIndex("UserId", "Data", "Tipo");

                    b.ToTable("LancamentosFinanceiros");
                });

            modelBuilder.Entity("Fatura.Server.Models.LembretePagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<string>("NomeConta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorConta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LembretesPagamento");
                });

            modelBuilder.Entity("Fatura.Server.Models.LembretePagamentoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LembretePagamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEnvio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LembretePagamentoId");

                    b.HasIndex("LembretePagamentoId", "DataReferencia", "TipoEnvio", "Canal")
                        .IsUnique();

                    b.ToTable("LembretesPagamentoHistoricos");
                });

            modelBuilder.Entity("Fatura.Server.Models.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompraId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompraRecorrenteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("CompraRecorrenteId");

                    b.HasIndex("FaturaId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("Fatura.Server.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContaFinanceiraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaFinanceiraId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("UserId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("Fatura.Server.Models.SimulacaoParcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId");

                    b.ToTable("SimulacaoParcelas");
                });

            modelBuilder.Entity("Fatura.Server.Models.Subcategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UserId", "CategoriaId", "Nome")
                        .IsUnique();

                    b.ToTable("Subcategorias");
                });

            modelBuilder.Entity("Fatura.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fatura.Server.Models.Categoria", b =>
                {
                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("Categorias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.Compra", b =>
                {
                    b.HasOne("Fatura.Server.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("ContaFinanceiraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.Fornecedor", "Fornecedor")
                        .WithMany("Compras")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("Compras")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaFinanceira");

                    b.Navigation("Fornecedor");

                    b.Navigation("Subcategoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.CompraRecorrente", b =>
                {
                    b.HasOne("Fatura.Server.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("ContaFinanceiraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("ComprasRecorrentes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaFinanceira");

                    b.Navigation("Subcategoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.ContaFinanceira", b =>
                {
                    b.HasOne("Fatura.Server.Models.InstituicaoFinanceira", "Instituicao")
                        .WithMany("Contas")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("ContasFinanceiras")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.FaturaEntity", b =>
                {
                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("Faturas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.Fornecedor", b =>
                {
                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("Fornecedores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.InstituicaoFinanceira", b =>
                {
                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("InstituicoesFinanceiras")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.LancamentoFinanceiro", b =>
                {
                    b.HasOne("Fatura.Server.Models.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.ContaFinanceira", "ContaFinanceira")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaFinanceiraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fatura.Server.Models.Subcategoria", "Subcategoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("LancamentosFinanceiros")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaFinanceira");

                    b.Navigation("Subcategoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.LembretePagamento", b =>
                {
                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("LembretesPagamento")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.LembretePagamentoHistorico", b =>
                {
                    b.HasOne("Fatura.Server.Models.LembretePagamento", "LembretePagamento")
                        .WithMany("Historicos")
                        .HasForeignKey("LembretePagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LembretePagamento");
                });

            modelBuilder.Entity("Fatura.Server.Models.Parcela", b =>
                {
                    b.HasOne("Fatura.Server.Models.Compra", "Compra")
                        .WithMany("Parcelas")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fatura.Server.Models.CompraRecorrente", "CompraRecorrente")
                        .WithMany("Parcelas")
                        .HasForeignKey("CompraRecorrenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fatura.Server.Models.FaturaEntity", "Fatura")
                        .WithMany("Parcelas")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Compra");

                    b.Navigation("CompraRecorrente");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Fatura.Server.Models.Simulacao", b =>
                {
                    b.HasOne("Fatura.Server.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("ContaFinanceiraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("Simulacoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaFinanceira");

                    b.Navigation("Subcategoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.SimulacaoParcela", b =>
                {
                    b.HasOne("Fatura.Server.Models.Simulacao", "Simulacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("Fatura.Server.Models.Subcategoria", b =>
                {
                    b.HasOne("Fatura.Server.Models.Categoria", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fatura.Server.Models.User", "User")
                        .WithMany("Subcategorias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fatura.Server.Models.Categoria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("Fatura.Server.Models.Compra", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Fatura.Server.Models.CompraRecorrente", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Fatura.Server.Models.ContaFinanceira", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Fatura.Server.Models.FaturaEntity", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Fatura.Server.Models.Fornecedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("Fatura.Server.Models.InstituicaoFinanceira", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("Fatura.Server.Models.LembretePagamento", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("Fatura.Server.Models.Simulacao", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Fatura.Server.Models.Subcategoria", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Fatura.Server.Models.User", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Compras");

                    b.Navigation("ComprasRecorrentes");

                    b.Navigation("ContasFinanceiras");

                    b.Navigation("Faturas");

                    b.Navigation("Fornecedores");

                    b.Navigation("InstituicoesFinanceiras");

                    b.Navigation("LancamentosFinanceiros");

                    b.Navigation("LembretesPagamento");

                    b.Navigation("Simulacoes");

                    b.Navigation("Subcategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
